chore: update

diff --git a/config/xinit/.config/xinit/xprofile b/config/xinit/.config/xinit/xprofile
--- a/config/xinit/.config/xinit/xprofile
+++ b/config/xinit/.config/xinit/xprofile
@@ -8,6 +8,7 @@ dunst &
 
 # faster keyboard
 setxkbmap -option caps:escape
+
 # xset r rate 210 40
 xset r rate 240 60
 # - 240: delay time before a held key begins to repeat
@@ -33,3 +34,12 @@ brillo -S 70
 # ===================== TRAY SYSTEM ===================
 
 ulauncher --hide-window &
+
+# =============== IBUS AUTO start ===============
+found_ibus_daemon=$(pgrep -x ibus-daemon > /dev/null && echo "Process found" || echo "Process not found")
+if [[ $found_ibus_daemon == "Process not found" ]]; then
+  ibus-daemon -drx &
+  echo 'ibus-daemon not found, starting in the background'
+else
+  echo 'ibus-daemon found'
+fi
