chore: update

diff --git a/config/xinit/.config/xinit/xprofile b/config/xinit/.config/xinit/xprofile
--- a/config/xinit/.config/xinit/xprofile
+++ b/config/xinit/.config/xinit/xprofile
@@ -31,16 +31,6 @@ copyq &
 # brightness
 brillo -S 70
 
-# =============== IBUS AUTO start ===============
-found_ibus_daemon=$(pgrep -x ibus-daemon > /dev/null && echo "Process found" || echo "Process not found")
-if [[ $found_ibus_daemon == "Process not found" ]]; then
-  ibus-daemon -drx &
-  sleep 0.5
-  echo 'ibus-daemon not found, starting in the background'
-else
-  echo 'ibus-daemon found'
-fi
-
 # ===================== TRAY SYSTEM ===================
 
 ulauncher --hide-window &
@@ -48,3 +38,13 @@ ulauncher --hide-window &
 # ===================== Screen Saver ==================
 
 xscreensaver --no-splash &
+
+# =============== IBUS AUTO start ===============
+found_ibus_daemon=$(pgrep -x ibus-daemon > /dev/null && echo "Process found" || echo "Process not found")
+if [[ $found_ibus_daemon == "Process not found" ]]; then
+  ibus-daemon -drx &
+  echo 'ibus-daemon not found, starting in the background'
+else
+  echo 'ibus-daemon found'
+fi
+
